// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package models

type Book struct {
	ID    int64   `db:"id" json:"id"`
	Title *string `db:"title" json:"title"`
	Year  *int64  `db:"year" json:"year"`
}

type BookSongJoin struct {
	ID               int64   `db:"id" json:"id"`
	BookID           *int64  `db:"book_id" json:"book_id"`
	SongID           *int64  `db:"song_id" json:"song_id"`
	PageNum          *string `db:"page_num" json:"page_num"`
	Text             *string `db:"text" json:"text"`
	WordsAttribution *string `db:"words_attribution" json:"words_attribution"`
	Keys             *string `db:"keys" json:"keys"`
	Times            *string `db:"times" json:"times"`
	Orientation      *string `db:"orientation" json:"orientation"`
}

type Leader struct {
	ID            int64    `db:"id" json:"id"`
	Name          *string  `db:"name" json:"name"`
	LessonCount   *int64   `db:"lesson_count" json:"lesson_count"`
	SongEntropy   *float64 `db:"song_entropy" json:"song_entropy"`
	Top20Count    *int64   `db:"top20_count" json:"top20_count"`
	LocationCount *int64   `db:"location_count" json:"location_count"`
}

type LeaderCoattendance struct {
}

type LeaderDetail struct {
	LeaderName          string `db:"leader_name" json:"leader_name"`
	LeaderTotalNumLeads int64  `db:"leader_total_num_leads" json:"leader_total_num_leads"`
	SongTitle           string `db:"song_title" json:"song_title"`
	PageNumber          string `db:"page_number" json:"page_number"`
	SongNumLeads        int64  `db:"song_num_leads" json:"song_num_leads"`
}

type LeaderMinute struct {
	LeaderID   int64  `db:"leader_id" json:"leader_id"`
	LeaderName string `db:"leader_name" json:"leader_name"`
	MinutesID  int64  `db:"minutes_id" json:"minutes_id"`
}

type LeaderNameAlias struct {
	ID       int64   `db:"id" json:"id"`
	LeaderID *int64  `db:"leader_id" json:"leader_id"`
	Name     *string `db:"name" json:"name"`
	Alias    *string `db:"alias" json:"alias"`
	Type     *string `db:"type" json:"type"`
}

type LeaderNameInvalid struct {
	ID   int64   `db:"id" json:"id"`
	Name *string `db:"name" json:"name"`
}

type LeaderNameMap struct {
	LeaderID int64  `db:"leader_id" json:"leader_id"`
	Name     string `db:"name" json:"name"`
}

type LeaderProfile struct {
	LeaderID          int64  `db:"leader_id" json:"leader_id"`
	Name              string `db:"name" json:"name"`
	LessonCount       int64  `db:"lesson_count" json:"lesson_count"`
	UniqueLessonCount int64  `db:"unique_lesson_count" json:"unique_lesson_count"`
	SingingCount      int64  `db:"singing_count" json:"singing_count"`
	FirstYear         int64  `db:"first_year" json:"first_year"`
	LastYear          int64  `db:"last_year" json:"last_year"`
}

type LeaderSinging struct {
}

type LeaderSongAttendance struct {
}

type LeaderSongStat struct {
	ID          int64  `db:"id" json:"id"`
	LeaderID    *int64 `db:"leader_id" json:"leader_id"`
	SongID      *int64 `db:"song_id" json:"song_id"`
	LessonCount *int64 `db:"lesson_count" json:"lesson_count"`
	LessonRank  *int64 `db:"lesson_rank" json:"lesson_rank"`
}

type LeaderYearStat struct {
	LeaderID    int64 `db:"leader_id" json:"leader_id"`
	Year        int64 `db:"year" json:"year"`
	LessonCount int64 `db:"lesson_count" json:"lesson_count"`
}

type LessonDetails struct {
	ID                     int64  `db:"id" json:"id"`
	Name                   string `db:"name" json:"name"`
	LeaderLessonCount      int64  `db:"leader_lesson_count" json:"leader_lesson_count"`
	LeaderLessonRank       int64  `db:"leader_lesson_rank" json:"leader_lesson_rank"`
	SongPage               string `db:"song_page" json:"song_page"`
	SongTitle              string `db:"song_title" json:"song_title"`
	LeaderTotalLessonCount int64  `db:"leader_total_lesson_count" json:"leader_total_lesson_count"`
	SongMeter              string `db:"song_meter" json:"song_meter"`
	SongKeys               string `db:"song_keys" json:"song_keys"`
	SongMusicAttribution   string `db:"song_music_attribution" json:"song_music_attribution"`
	SongWordsAttribution   string `db:"song_words_attribution" json:"song_words_attribution"`
}

type Location struct {
	ID            int64    `db:"id" json:"id"`
	Name          *string  `db:"name" json:"name"`
	URL           *string  `db:"url" json:"url"`
	Notes         *string  `db:"notes" json:"notes"`
	GpsLat        *float64 `db:"gps_lat" json:"gps_lat"`
	GpsLong       *float64 `db:"gps_long" json:"gps_long"`
	Address       *string  `db:"address" json:"address"`
	City          *string  `db:"city" json:"city"`
	County        *string  `db:"county" json:"county"`
	StateProvince *string  `db:"state_province" json:"state_province"`
	PostalCode    *string  `db:"postal_code" json:"postal_code"`
	Country       *string  `db:"country" json:"country"`
}

type Minute struct {
	ID          int64    `db:"id" json:"id"`
	Name        *string  `db:"Name" json:"name"`
	Location    *string  `db:"Location" json:"location"`
	Date        *string  `db:"Date" json:"date"`
	Minutes     *string  `db:"Minutes" json:"minutes"`
	Year        *int64   `db:"Year" json:"year"`
	IsDenson    *int64   `db:"IsDenson" json:"is_denson"`
	GoodCt      *int64   `db:"GoodCt" json:"good_ct"`
	ErrCt       *int64   `db:"ErrCt" json:"err_ct"`
	AmbCt       *int64   `db:"AmbCt" json:"amb_ct"`
	CorrCt      *int64   `db:"CorrCt" json:"corr_ct"`
	ProbCt      *int64   `db:"ProbCt" json:"prob_ct"`
	TotalCt     *int64   `db:"TotalCt" json:"total_ct"`
	ProbPercent *float64 `db:"ProbPercent" json:"prob_percent"`
	DensonYear  *float64 `db:"DensonYear" json:"denson_year"`
	AudioURL    *string  `db:"audio_url" json:"audio_url"`
	DateOrdinal *int64   `db:"DateOrdinal" json:"date_ordinal"`
	IsVirtual   *int64   `db:"IsVirtual" json:"is_virtual"`
}

type MinutesExpanded struct {
	Leader                string `db:"leader" json:"leader"`
	SongPageNumber        string `db:"song_page_number" json:"song_page_number"`
	SongTitle             string `db:"song_title" json:"song_title"`
	MinutesName           string `db:"minutes_name" json:"minutes_name"`
	MinutesYear           int64  `db:"minutes_year" json:"minutes_year"`
	MinutesDate           string `db:"minutes_date" json:"minutes_date"`
	MinuesLocation        string `db:"minues_location" json:"minues_location"`
	SongKeys              string `db:"song_keys" json:"song_keys"`
	SongTuneBy            string `db:"song_tune_by" json:"song_tune_by"`
	SongWordsBy           string `db:"song_words_by" json:"song_words_by"`
	LeaderTotalNumLessons int64  `db:"leader_total_num_lessons" json:"leader_total_num_lessons"`
	LeaderNumInTheTop20   int64  `db:"leader_num_in_the_top_20" json:"leader_num_in_the_top_20"`
	LocationName          string `db:"location_name" json:"location_name"`
	LocationState         string `db:"location_state" json:"location_state"`
	LocationCity          string `db:"location_city" json:"location_city"`
	LocationCountry       string `db:"location_country" json:"location_country"`
	LocationZipCode       string `db:"location_zip_code" json:"location_zip_code"`
}

type MinutesLocationJoin struct {
	ID         int64  `db:"id" json:"id"`
	MinutesID  *int64 `db:"minutes_id" json:"minutes_id"`
	LocationID *int64 `db:"location_id" json:"location_id"`
}

type MinutesSingingJoin struct {
	ID           int64  `db:"id" json:"id"`
	MinutesID    *int64 `db:"minutes_id" json:"minutes_id"`
	SingingID    *int64 `db:"singing_id" json:"singing_id"`
	SingingIndex *int64 `db:"singing_index" json:"singing_index"`
	SingingEnd   *int64 `db:"singing_end" json:"singing_end"`
}

type Singing struct {
	ID   int64   `db:"id" json:"id"`
	Name *string `db:"name" json:"name"`
}

type SingingDetails struct {
	MinutesID             int64  `db:"minutes_id" json:"minutes_id"`
	MinutesName           string `db:"minutes_name" json:"minutes_name"`
	MinutesLocation       string `db:"minutes_location" json:"minutes_location"`
	MinutesDate           string `db:"minutes_date" json:"minutes_date"`
	MinutesYear           int64  `db:"minutes_year" json:"minutes_year"`
	MinutesBody           string `db:"minutes_body" json:"minutes_body"`
	Singing               string `db:"singing" json:"singing"`
	LocationName          string `db:"location_name" json:"location_name"`
	LocationCountry       string `db:"location_country" json:"location_country"`
	LocationStateProvince string `db:"location_state_province" json:"location_state_province"`
	LocationCity          string `db:"location_city" json:"location_city"`
}

type SingingInfo struct {
	MinutesID       int64    `db:"minutes_id" json:"minutes_id"`
	LessonID        int64    `db:"lesson_id" json:"lesson_id"`
	SingingDate     DateTime `db:"singing_date" json:"singing_date"`
	SingingName     string   `db:"singing_name" json:"singing_name"`
	SingingState    string   `db:"singing_state" json:"singing_state"`
	SingingLocation string   `db:"singing_location" json:"singing_location"`
	NumberOfLessons int64    `db:"number_of_lessons" json:"number_of_lessons"`
	NumberOfLeaders int64    `db:"number_of_leaders" json:"number_of_leaders"`
}

type SingingLesson struct {
	SequenceNumber int64       `db:"sequence_number" json:"sequence_number"`
	LessonID       int64       `db:"lesson_id" json:"lesson_id"`
	SingingName    string      `db:"singing_name" json:"singing_name"`
	SingerName     string      `db:"singer_name" json:"singer_name"`
	SongPageNumber interface{} `db:"song_page_number" json:"song_page_number"`
	SongName       string      `db:"song_name" json:"song_name"`
	SongKey        interface{} `db:"song_key" json:"song_key"`
}

type Song struct {
	ID               int64   `db:"id" json:"id"`
	Title            *string `db:"title" json:"title"`
	Meter            *string `db:"meter" json:"meter"`
	MusicAttribution *string `db:"music_attribution" json:"music_attribution"`
	ThreeLiner       *int64  `db:"three_liner" json:"three_liner"`
}

type SongDetail struct {
	SongID           int64  `db:"song_id" json:"song_id"`
	PageNum          string `db:"page_num" json:"page_num"`
	Keys             string `db:"keys" json:"keys"`
	Times            string `db:"times" json:"times"`
	SongTitle        string `db:"song_title" json:"song_title"`
	SongMeter        string `db:"song_meter" json:"song_meter"`
	MusicAttribution string `db:"music_attribution" json:"music_attribution"`
	WordsAttribution string `db:"words_attribution" json:"words_attribution"`
}

type SongLeaderJoin struct {
	ID        int64   `db:"id" json:"id"`
	SongID    *int64  `db:"song_id" json:"song_id"`
	LeaderID  *int64  `db:"leader_id" json:"leader_id"`
	MinutesID *int64  `db:"minutes_id" json:"minutes_id"`
	LessonID  *int64  `db:"lesson_id" json:"lesson_id"`
	AudioURL  *string `db:"audio_url" json:"audio_url"`
}

type SongLeaderStat struct {
	Name          string  `db:"name" json:"name"`
	PageNum       *string `db:"page_num" json:"page_num"`
	Count         *int64  `db:"count" json:"count"`
	NumYears      int64   `db:"num_years" json:"num_years"`
	LedInLastYear int64   `db:"led_in_last_year" json:"led_in_last_year"`
}

type SongNeighbor struct {
	ID         int64  `db:"id" json:"id"`
	FromSongID *int64 `db:"from_song_id" json:"from_song_id"`
	ToSongID   *int64 `db:"to_song_id" json:"to_song_id"`
	Rank       *int64 `db:"rank" json:"rank"`
}

type SongStat struct {
	ID          int64  `db:"id" json:"id"`
	SongID      *int64 `db:"song_id" json:"song_id"`
	Year        *int64 `db:"year" json:"year"`
	LessonCount *int64 `db:"lesson_count" json:"lesson_count"`
	Rank        *int64 `db:"rank" json:"rank"`
}

type SongStatsTotal struct {
}
