// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
)

const getLeader = `-- name: GetLeader :one
SELECT
	COALESCE(name, ''),
	COALESCE(lesson_count, 0),
	COALESCE(top20_count, 0),
	COALESCE(location_count, 0)
FROM leaders
WHERE name = ?
`

type GetLeaderRow struct {
	Name          string `db:"name" json:"name"`
	LessonCount   int64  `db:"lesson_count" json:"lesson_count"`
	Top20Count    int64  `db:"top20_count" json:"top20_count"`
	LocationCount int64  `db:"location_count" json:"location_count"`
}

func (q *Queries) GetLeader(ctx context.Context, name *string) (GetLeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getLeader, name)
	var i GetLeaderRow
	err := row.Scan(
		&i.Name,
		&i.LessonCount,
		&i.Top20Count,
		&i.LocationCount,
	)
	return i, err
}

const getSingerConnectedness = `-- name: GetSingerConnectedness :one
SELECT
	CAST(COUNT(DISTINCT b.leader_id) AS REAL) / (SELECT COUNT(*) FROM leaders) AS connectedness
FROM song_leader_joins a
JOIN song_leader_joins b ON b.minutes_id = a.minutes_id AND b.leader_id != a.leader_id
WHERE a.leader_id = (SELECT id FROM leaders WHERE leaders.name = ?)
`

func (q *Queries) GetSingerConnectedness(ctx context.Context, name *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getSingerConnectedness, name)
	var connectedness int64
	err := row.Scan(&connectedness)
	return connectedness, err
}

const getSong = `-- name: GetSong :one
SELECT
	song_id, page_num, keys, times, song_title, song_meter, music_attribution, words_attribution
FROM song_details
WHERE page_num = ?
`

func (q *Queries) GetSong(ctx context.Context, pageNum string) (SongDetail, error) {
	row := q.db.QueryRowContext(ctx, getSong, pageNum)
	var i SongDetail
	err := row.Scan(
		&i.SongID,
		&i.PageNum,
		&i.Keys,
		&i.Times,
		&i.SongTitle,
		&i.SongMeter,
		&i.MusicAttribution,
		&i.WordsAttribution,
	)
	return i, err
}
