// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package models

import (
	"context"
)

const getActiveSingerConnectedness = `-- name: GetActiveSingerConnectedness :one
SELECT
	CAST(CAST(COUNT(DISTINCT b.leader_id) AS REAL) / CAST((SELECT COUNT(*) FROM leaders) AS REAL) AS REAL) AS connectedness
FROM active_song_leader_joins a
JOIN active_song_leader_joins b ON b.minutes_id = a.minutes_id AND b.leader_id != a.leader_id
WHERE a.leader_id = (SELECT id FROM leaders WHERE leaders.name = ?)
`

func (q *Queries) GetActiveSingerConnectedness(ctx context.Context, name *string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getActiveSingerConnectedness, name)
	var connectedness float64
	err := row.Scan(&connectedness)
	return connectedness, err
}

const getLeader = `-- name: GetLeader :one
SELECT
	COALESCE(name, ''),
	COALESCE(lesson_count, 0),
	COALESCE(top20_count, 0),
	COALESCE(location_count, 0)
FROM leaders
WHERE name = ?
`

type GetLeaderRow struct {
	Name          string `db:"name" json:"name"`
	LessonCount   int64  `db:"lesson_count" json:"lesson_count"`
	Top20Count    int64  `db:"top20_count" json:"top20_count"`
	LocationCount int64  `db:"location_count" json:"location_count"`
}

func (q *Queries) GetLeader(ctx context.Context, name *string) (GetLeaderRow, error) {
	row := q.db.QueryRowContext(ctx, getLeader, name)
	var i GetLeaderRow
	err := row.Scan(
		&i.Name,
		&i.LessonCount,
		&i.Top20Count,
		&i.LocationCount,
	)
	return i, err
}

const getLeaderActiveYears = `-- name: GetLeaderActiveYears :one
SELECT
    CAST(COALESCE(MIN(m.year), 0) AS INTEGER) AS first_year,
    CAST(COALESCE(MAX(m.year), 0) AS INTEGER) AS last_year,
    CAST(COALESCE(MAX(m.year) - MIN(m.year) + 1, 0) AS INTEGER) AS years_active,
    CAST(CASE WHEN MAX(m.year) >= (SELECT MAX(year) FROM minutes) - 5 THEN 1 ELSE 0 END AS INTEGER) AS is_active
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN minutes AS m ON m.id = slj.minutes_id
WHERE lnm.name = ?
`

type GetLeaderActiveYearsRow struct {
	FirstYear   int64 `db:"first_year" json:"first_year"`
	LastYear    int64 `db:"last_year" json:"last_year"`
	YearsActive int64 `db:"years_active" json:"years_active"`
	IsActive    int64 `db:"is_active" json:"is_active"`
}

func (q *Queries) GetLeaderActiveYears(ctx context.Context, name string) (GetLeaderActiveYearsRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderActiveYears, name)
	var i GetLeaderActiveYearsRow
	err := row.Scan(
		&i.FirstYear,
		&i.LastYear,
		&i.YearsActive,
		&i.IsActive,
	)
	return i, err
}

const getLeaderMajorMinorCounts = `-- name: GetLeaderMajorMinorCounts :one
SELECT
    CAST(COALESCE(SUM(CASE WHEN bsj.keys LIKE '%Major%' THEN 1 ELSE 0 END), 0) AS INTEGER) AS major_count,
    CAST(COALESCE(SUM(CASE WHEN bsj.keys LIKE '%Minor%' THEN 1 ELSE 0 END), 0) AS INTEGER) AS minor_count
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN book_song_joins AS bsj ON slj.song_id = bsj.song_id AND bsj.book_id = 2
WHERE lnm.name = ?
`

type GetLeaderMajorMinorCountsRow struct {
	MajorCount int64 `db:"major_count" json:"major_count"`
	MinorCount int64 `db:"minor_count" json:"minor_count"`
}

func (q *Queries) GetLeaderMajorMinorCounts(ctx context.Context, name string) (GetLeaderMajorMinorCountsRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderMajorMinorCounts, name)
	var i GetLeaderMajorMinorCountsRow
	err := row.Scan(&i.MajorCount, &i.MinorCount)
	return i, err
}

const getLeaderTopActiveSingingBuddy = `-- name: GetLeaderTopActiveSingingBuddy :one
SELECT CAST(COALESCE(lna2.name, l2.name, '') AS TEXT) AS buddy_name, CAST(COUNT(DISTINCT slj2.minutes_id) AS INTEGER) AS singing_count
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN active_song_leader_joins AS slj2 ON slj2.minutes_id = slj.minutes_id AND slj2.leader_id != slj.leader_id
JOIN leaders AS l2 ON l2.id = slj2.leader_id
LEFT JOIN (SELECT alias, MIN(name) AS name FROM leader_name_aliases WHERE leader_id IS NOT NULL GROUP BY alias) AS lna2 ON lna2.alias = l2.name
LEFT JOIN leader_name_invalid AS inv ON inv.name = l2.name
WHERE lnm.name = ?
AND inv.name IS NULL
GROUP BY slj2.leader_id
ORDER BY singing_count DESC
LIMIT 1
`

type GetLeaderTopActiveSingingBuddyRow struct {
	BuddyName    string `db:"buddy_name" json:"buddy_name"`
	SingingCount int64  `db:"singing_count" json:"singing_count"`
}

func (q *Queries) GetLeaderTopActiveSingingBuddy(ctx context.Context, name string) (GetLeaderTopActiveSingingBuddyRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderTopActiveSingingBuddy, name)
	var i GetLeaderTopActiveSingingBuddyRow
	err := row.Scan(&i.BuddyName, &i.SingingCount)
	return i, err
}

const getLeaderTopMajorKey = `-- name: GetLeaderTopMajorKey :one
SELECT CAST(COALESCE(bsj.keys, '') AS TEXT) AS top_key, CAST(COUNT(*) AS INTEGER) AS lead_count
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN book_song_joins AS bsj ON slj.song_id = bsj.song_id AND bsj.book_id = 2
WHERE lnm.name = ?
AND bsj.keys LIKE '%Major%' AND bsj.keys NOT LIKE '%Minor%'
GROUP BY bsj.keys
ORDER BY lead_count DESC
LIMIT 1
`

type GetLeaderTopMajorKeyRow struct {
	TopKey    string `db:"top_key" json:"top_key"`
	LeadCount int64  `db:"lead_count" json:"lead_count"`
}

func (q *Queries) GetLeaderTopMajorKey(ctx context.Context, name string) (GetLeaderTopMajorKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderTopMajorKey, name)
	var i GetLeaderTopMajorKeyRow
	err := row.Scan(&i.TopKey, &i.LeadCount)
	return i, err
}

const getLeaderTopMinorKey = `-- name: GetLeaderTopMinorKey :one
SELECT CAST(COALESCE(bsj.keys, '') AS TEXT) AS top_key, CAST(COUNT(*) AS INTEGER) AS lead_count
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN book_song_joins AS bsj ON slj.song_id = bsj.song_id AND bsj.book_id = 2
WHERE lnm.name = ?
AND bsj.keys LIKE '%Minor%' AND bsj.keys NOT LIKE '%Major%'
GROUP BY bsj.keys
ORDER BY lead_count DESC
LIMIT 1
`

type GetLeaderTopMinorKeyRow struct {
	TopKey    string `db:"top_key" json:"top_key"`
	LeadCount int64  `db:"lead_count" json:"lead_count"`
}

func (q *Queries) GetLeaderTopMinorKey(ctx context.Context, name string) (GetLeaderTopMinorKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderTopMinorKey, name)
	var i GetLeaderTopMinorKeyRow
	err := row.Scan(&i.TopKey, &i.LeadCount)
	return i, err
}

const getLeaderTopSingingBuddy = `-- name: GetLeaderTopSingingBuddy :one
SELECT CAST(COALESCE(lna2.name, l2.name, '') AS TEXT) AS buddy_name, CAST(COUNT(DISTINCT slj2.minutes_id) AS INTEGER) AS singing_count
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN song_leader_joins AS slj2 ON slj2.minutes_id = slj.minutes_id AND slj2.leader_id != slj.leader_id
JOIN leaders AS l2 ON l2.id = slj2.leader_id
LEFT JOIN (SELECT alias, MIN(name) AS name FROM leader_name_aliases WHERE leader_id IS NOT NULL GROUP BY alias) AS lna2 ON lna2.alias = l2.name
LEFT JOIN leader_name_invalid AS inv ON inv.name = l2.name
WHERE lnm.name = ?
AND inv.name IS NULL
GROUP BY slj2.leader_id
ORDER BY singing_count DESC
LIMIT 1
`

type GetLeaderTopSingingBuddyRow struct {
	BuddyName    string `db:"buddy_name" json:"buddy_name"`
	SingingCount int64  `db:"singing_count" json:"singing_count"`
}

func (q *Queries) GetLeaderTopSingingBuddy(ctx context.Context, name string) (GetLeaderTopSingingBuddyRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderTopSingingBuddy, name)
	var i GetLeaderTopSingingBuddyRow
	err := row.Scan(&i.BuddyName, &i.SingingCount)
	return i, err
}

const getLeaderTopState = `-- name: GetLeaderTopState :one
SELECT CAST(COALESCE(loc.state_province, '') AS TEXT) AS state, CAST(COUNT(*) AS INTEGER) AS lead_count
FROM song_leader_joins AS slj
JOIN leader_name_map AS lnm ON lnm.leader_id = slj.leader_id
JOIN minutes AS m ON m.id = slj.minutes_id
JOIN minutes_location_joins AS mlj ON mlj.minutes_id = m.id
JOIN locations AS loc ON loc.id = mlj.location_id
WHERE lnm.name = ?
AND loc.state_province != '' AND loc.state_province IS NOT NULL
GROUP BY loc.state_province
ORDER BY lead_count DESC
LIMIT 1
`

type GetLeaderTopStateRow struct {
	State     string `db:"state" json:"state"`
	LeadCount int64  `db:"lead_count" json:"lead_count"`
}

func (q *Queries) GetLeaderTopState(ctx context.Context, name string) (GetLeaderTopStateRow, error) {
	row := q.db.QueryRowContext(ctx, getLeaderTopState, name)
	var i GetLeaderTopStateRow
	err := row.Scan(&i.State, &i.LeadCount)
	return i, err
}

const getSingerConnectedness = `-- name: GetSingerConnectedness :one
SELECT
	CAST(CAST(COUNT(DISTINCT b.leader_id) AS REAL) / CAST((SELECT COUNT(*) FROM leaders) AS REAL) AS REAL) AS connectedness
FROM song_leader_joins a
JOIN song_leader_joins b ON b.minutes_id = a.minutes_id AND b.leader_id != a.leader_id
WHERE a.leader_id = (SELECT id FROM leaders WHERE leaders.name = ?)
`

func (q *Queries) GetSingerConnectedness(ctx context.Context, name *string) (float64, error) {
	row := q.db.QueryRowContext(ctx, getSingerConnectedness, name)
	var connectedness float64
	err := row.Scan(&connectedness)
	return connectedness, err
}

const getSong = `-- name: GetSong :one
SELECT
	song_id, page_num, keys, times, song_title, song_meter, music_attribution, words_attribution
FROM song_details
WHERE page_num = ?
`

func (q *Queries) GetSong(ctx context.Context, pageNum string) (SongDetail, error) {
	row := q.db.QueryRowContext(ctx, getSong, pageNum)
	var i SongDetail
	err := row.Scan(
		&i.SongID,
		&i.PageNum,
		&i.Keys,
		&i.Times,
		&i.SongTitle,
		&i.SongMeter,
		&i.MusicAttribution,
		&i.WordsAttribution,
	)
	return i, err
}
